### ISSUE TITLE
Merging forces with https://github.com/Azathothas/Toolpacks ?

### ISSUE THREAD

**Issue by xplshn** [mosajjal/binary-tools#3]
Azathothas maintains two repos, one with essential system tools, and other with misc stuff. There is a tg group, I proposed a collaboration, his repo contains 560+ binaries, and the other contains 360+ binaries. Its all automated, it'd be great if you could collaborate with C based projects, which I am not good at statically linking. Anyways! This is great! Can I use it for my little "Binary Manager"?

**Comment by mosajjal** [comment]
hey. mate, most of these builds are from scratch and don't have a recipe or a Makefile associate with them. for bigger ones (like Wireshark etc), happy to participate in building `Dockerfile`s that spit out static binaries and make the process reproducible but currently I don't have any of those. will close this but feel free to reach out if you guys start something and I can pitch it.

**Comment by xplshn** [comment]
The build process is just a GH runner and a one liner, that is how most thing are built in the toolpacks repo, which contains a lot of things made primarily in Go and Rust, the base repo contains busybox, toybox, coreutils, ncurses' utilities, curl, wget, etc. No Docker or anything. Thank you anyways! Great work!
